### PR TITLE
New feature: revoke cert

### PR DESCRIPTION
**Pull request by grzs**
---
name: Revoke cert
about: If request state is 'absent' the certificate will be revoked

---

**Describe the change**

Locate the user certificate file in ca directory and performs the following steps:
- init crlnumber file if not exists
- use openssl ca -revoke to revoke certificate
- delete user certificate file from server if the revoke command was successful
- generate crl.pem

**Testing**
A user certificate had been generated in an arbitrary server has been revoked.

```
  roles:
    - role: robertdebock.ca
      vars:
        ca_init: yes
        ca_requests:
          - name: test
            state: absent
```

### CODE REVIEW

**Comment by robertdebock** [comment]
That looks pretty good. I'm a bit afraid what it will do to the roles that depend on this role:

- [ ] ansible-role-openvpn

I'll manually test these roles before merging, please give me some time for it.

**Comment by grzs** [comment]
Actually, I've made these modifications in order to solve the problems occured by using the openvpn role. Please take a look at my fork of your openvpn role. The current branch is '[config-options'](https://github.com/grzs/ansible-role-openvpn/tree/config_options). 

But I suppose your openvpn role won't brake even if you leave it unmodified. If you need any kind of explanations regarding my commits, don't hesitate to write.

**Comment by robertdebock** [comment]
It looks pretty good, the only change I needed is here:

```diff
$  git diff
diff --git a/tasks/main.yml b/tasks/main.yml
index 6bac365..7f56f2f 100644
--- a/tasks/main.yml
+++ b/tasks/main.yml
@@ -16,7 +16,8 @@
   openssl_privatekey:
     path: "{{ ca_openssl_path }}/{{ ca_privatekey_path }}"
     passphrase: "{{ ca_passphrase }}"
-    cipher: aes256
+    # cipher: aes256
+    cipher: auto
 
 - name: generate ca certificate signing request
   openssl_csr:
```

I'm not sure what the error message was, but is that something you could change?

Once again, thanks for keeping you patience!

**Comment by grzs** [comment]
Hello,

I ran your openssl role before the ca role, and I guess it has installed a
list of available ciphers. It could have been an option to choose with auto
as default.

I am glad that I could contribute.

Robert de Bock <notifications@github.com> ezt írta (időpont: 2020. szept.
18., P, 14:24):

**Comment by robertdebock** [comment]
Ready to merge.

**Pull request merged**
